import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/providers/query.provider";
import { HeroUIProvider } from "@heroui/system";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased z-0`}
      >
        {/* Logo at top left using Tailwind, no navbar or black background */}
        <HeroUIProvider>
          <div className="absolute -top-6 left-4">
            <a href="/">
              <img
                src="/tapal-tea-logo.jpg"
                alt="Tapal Tea Logo"
                className="h-40 w-[12.9rem] object-contain"
              />
            </a>
          </div>
          <QueryProvider>{children}</QueryProvider>
        </HeroUIProvider>
      </body>
    </html>
  );
}
