import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/providers/query.provider";
import { QueryClientProvider } from "@tanstack/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Logo at top left using Tailwind, no navbar or black background */}
        <div className="absolute -top-6 left-4 z-20">
          <a href="/">
            <img
              src="/tapal-tea-logo.png"
              alt="Tapal Tea Logo"
              className="h-40 w-[12.9rem] object-contain"
            />
          </a>
        </div>
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
